[dhan]
client_id = "1000007751"
access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzg2MDUyNTI0LCJpYXQiOjE3ODU5NjYxMjQsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMDAwMDA3NzUxIn0.BDU6j-n9Nc9ixHrDpRN5UZ-qmo4H3jFXTNnQrak1nStssOhYuYGTbJYBKgSntWTW_-iYUVBXVsOfsNG1CegTtw"
